server:
  host: "0.0.0.0"
  port: "8081"
  read_timeout: 20s
  write_timeout: 20s
  shutdown_timeout: 20s
  routes:
    create:
      fail_timeout: 10s
kafka:
  address: 
    - "0.0.0.0:9092"
  topic: "tasks"
  batch_timeout: 50ms
  required_acks: -1
  allow_topic_creation: true