server:
  host: "0.0.0.0"
  port: "8081"
  read_timeout: 20s
  write_timeout: 20s
  shutdown_timeout: 20s
sqlite3:
  path: ".tasks.db"
kafka:
  address: 
    - "0.0.0.0:9092"
  topic: "tasks-events"
  batch_timeout: 100ms
  required_acks: 1